# ===== Base de datos local (NO subir al repo) =====
spring.datasource.url=jdbc:postgresql://localhost:5433/replay_service
spring.datasource.username=postgres
spring.datasource.password=Calculadora2020.